version: '3.8'

services:
  redis:
    image: redis/redis-stack-server
    hostname: redis
    links:
      - redis-commander
    ports:
      - 6379:6379 # redis server
      - 8001:8001 # redis insight

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - 8081:8081
    
  spring:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    environment:
      - SPRING_AI_VECTORSTORE_REDIS_URI=redis://redis:6379